[alembic]
script_location = db_migrations
prepend_sys_path = .

sqlalchemy.url = sqlite:///./_lanproj_init.lanproj

[loggers]
keys = root,sqlalchemy,alembic
qualname = %(qualname)s
handlers = console
level = INFO

[handlers]
keys = console
handlers = console
class = StreamHandler
args = (sys.stderr,)

[formatters]
keys = generic
formatters = generic
class = %(class)s
format = %(levelname)-5.5s [%(name)s] %(message)s

